import type { FieldError } from "./commentModeration";

const ru = {
  language: "Язык",
  themeLight: "Светлая тема",
  themeDark: "Тёмная тема",
  navMenu: "Меню",
  navLunch: "Ланч",
  navBrunch: "Бранч",
  navDelivery: "С собой",
  navContacts: "Контакты",
  book: "Забронировать",
  bookTable: "Забронировать стол",
  takeawayCta: "Заказать на вынос",
  h1: "Деликатная Азия",
  taglineLine1: "Искусство баланса",
  taglineLine2: "между Востоком и Европой.",
  cart: "Корзина",
  closeCart: "Закрыть корзину",
  clearCart: "Очистить корзину",
  checkout: "Оформить заказ",
  pickupToday: "самовывоз сегодня",
  menu: "Меню",
  allMenu: "Всё меню",
  allHits: "Все хиты",
  businessLunch: "Бизнес-ланч",
  brunch: "Бранч",
  lunchTile: "Будни 12:00–16:00. Салат, суп и горячее — комплекс или по отдельности.",
  lunchText:
    "По будням с 12:00 до 16:00 — ланч: салат, суп и второе. Можно взять вместе или по одному. Тот же зал, дневной ритм.",
  lunchSetLater: "Состав комплекса на конкретный день появится позже",
  brunchHours: "Сб–вс 11:00–15:00",
  brunchTile: "Сб–вс 11:00–15:00. Европейские завтраки в том же зале.",
  brunchText:
    "По субботам и воскресеньям с 11:00 до 15:00 в UMI бранч. Европейские завтраки в том же зале, куда вечером приходят на том ям и стейк. Если компания — стол лучше забронировать.",
  aggregatorsTitle: "Заказать с доставкой",
  aggregatorsText:
    "Доставку везут агрегаторы. На вынос можно оформить у нас — заявкой, без оплаты на сайте.",
  collectTakeaway: "Собрать заказ на вынос",
  dayLunchKicker: "Бизнес-ланч",
  dayLunchTitle: "Дневной ритм",
  dayBrunchKicker: "Бранч",
  dayBrunchTitle: "Выходные",
  interiorTitle: "О нас и интерьер",
  interiorLead:
    "Один зал в центре Гомеля. Азиатское ядро и европейские блюда — рядом. Частично открытая кухня, барная стойка, закуток для небольшой компании.",
  instagramPrefix: "Наш инстаграм:",
  findUs: "Как найти",
  route: "Маршрут",
  contactsTitle: "Контакты",
  privacyLink: "Политика обработки персональных данных",
  privacyLinkShort: "Политике",
  privacySite: "Сайт",
  consentPdBooking: "Я соглашаюсь на обработку персональных данных в целях заявки на бронь стола согласно",
  consentPdTakeaway: "Я соглашаюсь на обработку персональных данных в целях заявки на вынос согласно",
  consentTelegramBefore:
    "Я соглашаюсь на передачу данных заявки в Telegram за пределы Республики Беларусь и проинформирован(а) о рисках, указанных в",
  consentTelegramAfter: "Без этого согласия заявку с сайта отправить нельзя.",
  consentNeed: "Чтобы отправить заявку, отметьте оба согласия.",
  noParking: "Парковки нет.",
  deliveryTitle: "Заказ с собой",
  deliveryLead:
    "Самовывоз из ресторана UMI — заявкой на сайте. Доставку везут агрегаторы, корзины и оплаты у нас нет.",
  deliveryHeading: "Доставка",
  bookingTitle: "Забронировать стол",
  bookingLead: "Имя, телефон, дата и время. Заявка не бронь — подтвердим звонком.",
  bookingHint: "Заявка не бронь. Подтвердим по телефону.",
  bookingSent: "Заявку получили, подтвердим по телефону.",
  takeawayTitle: "Заказ на вынос",
  takeawayHint: "Для оформления заказа требуется подтверждение по телефону.",
  takeawaySent: "Заявку получили, перезвоним.",
  name: "Имя",
  phone: "Телефон",
  date: "Дата",
  time: "Время",
  timeToday: "Время сегодня",
  guests: "Гостей",
  persons: "Персон",
  comment: "Комментарий",
  website: "Сайт",
  phoneTitle: "Только цифры, «+» только в начале, до 13 символов",
  nameOneWordTitle: "Одно слово, без пробелов",
  sum: "Сумма:",
  addMore: "Добавить ещё",
  kitchenClosed: "Сегодня кухня уже не принимает вынос. Позвоните нам или приходите завтра.",
  send: "Отправить заявку",
  call: "Позвонить",
  openRequest: "Открыть заявку",
  close: "Закрыть",
  hoursAria: "Часы",
  minutesAria: "Минуты",
  showDesc: "Показать состав",
  hideDesc: "Скрыть состав",
  add: "Добавить",
  less: "Меньше",
  more: "Больше",
  prevSection: "Предыдущий раздел",
  nextSection: "Следующий раздел",
  closeMenu: "Закрыть меню",
  openMenu: "Открыть меню",
  byn: "белорусский рубль",
  zoomOut: "Уменьшить",
  zoomIn: "Увеличить",
  prevPhoto: "Предыдущее фото",
  nextPhoto: "Следующее фото",
  zoomHint: "Щипок, колёсико или двойной тап — увеличить",
  hoursDays: ["Пн", "Вт–Чт", "Пт", "Сб", "Вс"],
  city: "Гомель",
  address: "ул. Кирова, 35",
  addressFull: "ул. Кирова, 35, Гомель",
  landmark: "угол Кирова и Комсомольской, возле кольца, остановка БелГУТ",
  floor: "этаж 1",
  homeSeo:
    "UMI — камерный ресторан в центре Гомеля. В меню азиатское ядро и европейские блюда: том ям и рамен рядом с пастой и стейком, роллы — рядом с вителло тоннато. Вечером — стол в зале, днём — ланч, в выходные — бранч. Стол бронируют на сайте, заказ с собой — заявкой, доставку везут агрегаторы.",
  dishAltSuffix: " — ресторан UMI Гомель",
  openPhoto: "Открыть фото:",
  removeDish: "Убрать",
  sendFailBooking: "Не удалось отправить заявку. Позвоните нам — подтвердим стол по телефону.",
  sendFailTakeaway: "Не удалось отправить заявку. Позвоните нам — подтвердим вынос по телефону.",
  emptyCart: "Добавьте хотя бы одно блюдо.",
  pickupLine: (address: string, open: string, close: string) =>
    `Самовывоз, ${address}. Сегодня ${open}–${close}.`,
  hoursLine: (address: string, hours: string) => `${address}. ${hours}.`,
  contactsLine: (name: string, address: string, floor: string) => `${name}, ${address}, ${floor}`,
  categorySeoTitle: (h1: string) => `${h1} — UMI Гомель`,
  categorySeoDescription: (title: string) => `${title} в ресторане UMI в Гомеле.`,
  seo: {
    "/": {
      title: "UMI — ресторан в Гомеле | Деликатная Азия",
      description:
        "Камерный зал в центре Гомеля: азиатское ядро и европейские блюда. Забронировать стол, бизнес-ланч, бранч, заказ с собой.",
    },
    "/menu": {
      title: "Меню ресторана UMI в Гомеле",
      description: "Стартеры, салаты и поке, супы, вок и паста, суши и роллы, десерты. Азия и Европа в одном меню.",
    },
    "/lunch": {
      title: "Бизнес-ланч в Гомеле — UMI",
      description:
        "Ланч по будням с 12:00 до 16:00: салат, суп и второе — вместе или по одному. Ресторан UMI, центр Гомеля.",
    },
    "/brunch": {
      title: "Бранч в Гомеле на выходных — UMI",
      description: "Бранч в субботу и воскресенье с 11:00 до 15:00 в ресторане UMI. Забронировать стол в центре Гомеля.",
    },
    "/delivery": {
      title: "Заказ с собой — UMI Гомель",
      description: "Самовывоз из ресторана UMI. Заявка на сайте, доставка — в агрегаторах.",
    },
    "/booking": {
      title: "Забронировать стол — UMI Гомель",
      description: "Бронь стола в ресторане UMI: имя, телефон, дата и время. Подтвердим звонком. Кирова, 35.",
    },
    "/contacts": {
      title: "Контакты UMI — Гомель, Кирова 35",
      description:
        "Ресторан UMI: ул. Кирова, 35, Гомель. Телефон +375 29 308-55-56. Часы работы, Instagram umi_gomel.",
    },
    "/privacy": {
      title: "Политика персональных данных — UMI Гомель",
      description:
        "Как ресторан UMI обрабатывает заявки на бронь и вынос, передача в Telegram и файлы cookie.",
    },
  },
  err: {
    commentLong: "Комментарий слишком длинный",
    noLinks: "В комментарии нельзя указывать ссылки",
    noProfanity: "Пожалуйста, без грубых слов — напишите иначе",
    needName: "Укажите имя",
    nameLong: "Имя слишком длинное",
    nameOneWord: "Имя — одно слово, без пробелов",
    needPhone: "Укажите телефон",
    phoneLong: "Телефон: максимум 13 символов",
    phoneFormat: "Только цифры, «+» можно поставить в начале",
  } satisfies Record<FieldError, string>,
};

const en: typeof ru = {
  language: "Language",
  themeLight: "Light theme",
  themeDark: "Dark theme",
  navMenu: "Menu",
  navLunch: "Lunch",
  navBrunch: "Brunch",
  navDelivery: "Takeaway",
  navContacts: "Contacts",
  book: "Book a table",
  bookTable: "Book a table",
  takeawayCta: "Order takeaway",
  h1: "Delicate Asia",
  taglineLine1: "The art of balance",
  taglineLine2: "between East and Europe.",
  cart: "Cart",
  closeCart: "Close cart",
  clearCart: "Clear cart",
  checkout: "Checkout",
  pickupToday: "pickup today",
  menu: "Menu",
  allMenu: "Full menu",
  allHits: "All hits",
  businessLunch: "Business lunch",
  brunch: "Brunch",
  lunchTile: "Weekdays 12:00–16:00. Salad, soup and a main — as a combo or separately.",
  lunchText:
    "Weekdays from 12:00 to 16:00 — lunch: salad, soup and a main. Take the combo or any dish on its own. Same room, daytime pace.",
  lunchSetLater: "The combo for a given day will appear later",
  brunchHours: "Sat–Sun 11:00–15:00",
  brunchTile: "Sat–Sun 11:00–15:00. European breakfasts in the same room.",
  brunchText:
    "Saturdays and Sundays from 11:00 to 15:00, UMI serves brunch. European breakfasts in the same room where evenings bring tom yum and steak. For a group, better book a table.",
  aggregatorsTitle: "Order delivery",
  aggregatorsText: "Delivery is handled by aggregators. Takeaway can be arranged with us — as a request, with no payment on the site.",
  collectTakeaway: "Build a takeaway order",
  dayLunchKicker: "Business lunch",
  dayLunchTitle: "Daytime pace",
  dayBrunchKicker: "Brunch",
  dayBrunchTitle: "Weekends",
  interiorTitle: "About us and the interior",
  interiorLead:
    "One room in the centre of Gomel. An Asian core and European dishes — side by side. A partly open kitchen, a bar counter, a nook for a small group.",
  instagramPrefix: "Our Instagram:",
  findUs: "How to find us",
  route: "Directions",
  contactsTitle: "Contacts",
  privacyLink: "Personal data processing policy",
  privacyLinkShort: "the Policy",
  privacySite: "Website",
  consentPdBooking: "I agree to the processing of personal data for a table request under",
  consentPdTakeaway: "I agree to the processing of personal data for a takeaway request under",
  consentTelegramBefore:
    "I agree to transfer the request data via Telegram outside Belarus and I have been informed of the risks in",
  consentTelegramAfter: "Without this consent a request cannot be sent from the site.",
  consentNeed: "Tick both consents to send the request.",
  noParking: "No parking.",
  deliveryTitle: "Takeaway",
  deliveryLead:
    "Pickup from UMI is a request on the site. Delivery is handled by aggregators; we have no cart checkout or payments.",
  deliveryHeading: "Delivery",
  bookingTitle: "Book a table",
  bookingLead: "Name, phone, date and time. A request is not a booking — we confirm by call.",
  bookingHint: "A request is not a booking. We will confirm by phone.",
  bookingSent: "We have the request and will confirm by phone.",
  takeawayTitle: "Takeaway order",
  takeawayHint: "The order needs confirmation by phone.",
  takeawaySent: "We have the request and will call you back.",
  name: "Name",
  phone: "Phone",
  date: "Date",
  time: "Time",
  timeToday: "Time today",
  guests: "Guests",
  persons: "People",
  comment: "Comment",
  website: "Website",
  phoneTitle: "Digits only, “+” at the start if needed, up to 13 characters",
  nameOneWordTitle: "One word, no spaces",
  sum: "Total:",
  addMore: "Add more",
  kitchenClosed: "The kitchen is no longer taking takeaway today. Call us or come tomorrow.",
  send: "Send request",
  call: "Call",
  openRequest: "Open the form",
  close: "Close",
  hoursAria: "Hours",
  minutesAria: "Minutes",
  showDesc: "Show description",
  hideDesc: "Hide description",
  add: "Add",
  less: "Less",
  more: "More",
  prevSection: "Previous section",
  nextSection: "Next section",
  closeMenu: "Close menu",
  openMenu: "Open menu",
  byn: "Belarusian ruble",
  zoomOut: "Zoom out",
  zoomIn: "Zoom in",
  prevPhoto: "Previous photo",
  nextPhoto: "Next photo",
  zoomHint: "Pinch, scroll wheel or double-tap to zoom",
  hoursDays: ["Mon", "Tue–Thu", "Fri", "Sat", "Sun"],
  city: "Gomel",
  address: "35 Kirova St.",
  addressFull: "35 Kirova St., Gomel",
  landmark: "corner of Kirova and Komsomolskaya, near the roundabout, BelGUT stop",
  floor: "1st floor",
  homeSeo:
    "UMI is a small restaurant in the centre of Gomel. The menu has an Asian core and European dishes: tom yum and ramen next to pasta and steak, rolls next to vitello tonnato. Evenings are a table in the room, daytime is lunch, weekends are brunch. Tables are booked on the site, takeaway is a request, delivery is through aggregators.",
  dishAltSuffix: " — UMI restaurant, Gomel",
  openPhoto: "Open photo:",
  removeDish: "Remove",
  sendFailBooking: "Could not send the request. Call us — we will confirm the table by phone.",
  sendFailTakeaway: "Could not send the request. Call us — we will confirm takeaway by phone.",
  emptyCart: "Add at least one dish.",
  pickupLine: (address, open, close) => `Pickup, ${address}. Today ${open}–${close}.`,
  hoursLine: (address, hours) => `${address}. ${hours}.`,
  contactsLine: (name, address, floor) => `${name}, ${address}, ${floor}`,
  categorySeoTitle: (h1) => `${h1} — UMI Gomel`,
  categorySeoDescription: (title) => `${title} at UMI restaurant in Gomel.`,
  seo: {
    "/": {
      title: "UMI — restaurant in Gomel | Delicate Asia",
      description:
        "A small room in the centre of Gomel: an Asian core and European dishes. Book a table, business lunch, brunch, takeaway.",
    },
    "/menu": {
      title: "UMI restaurant menu in Gomel",
      description: "Starters, salads and poke, soups, wok and pasta, sushi and rolls, desserts. Asia and Europe on one menu.",
    },
    "/lunch": {
      title: "Business lunch in Gomel — UMI",
      description:
        "Lunch on weekdays from 12:00 to 16:00: salad, soup and a main — together or on their own. UMI restaurant, centre of Gomel.",
    },
    "/brunch": {
      title: "Weekend brunch in Gomel — UMI",
      description: "Brunch on Saturday and Sunday from 11:00 to 15:00 at UMI. Book a table in the centre of Gomel.",
    },
    "/delivery": {
      title: "Takeaway — UMI Gomel",
      description: "Pickup from UMI restaurant. Request on the site; delivery is through aggregators.",
    },
    "/booking": {
      title: "Book a table — UMI Gomel",
      description: "Book a table at UMI: name, phone, date and time. We confirm by call. 35 Kirova St.",
    },
    "/contacts": {
      title: "UMI contacts — Gomel, 35 Kirova St.",
      description:
        "UMI restaurant: 35 Kirova St., Gomel. Phone +375 29 308-55-56. Opening hours, Instagram umi_gomel.",
    },
    "/privacy": {
      title: "Personal data policy — UMI Gomel",
      description: "How restaurant UMI handles table and takeaway requests, Telegram transfer and cookies.",
    },
  },
  err: {
    commentLong: "The comment is too long",
    noLinks: "Links are not allowed in the comment",
    noProfanity: "Please rephrase without rude language",
    needName: "Enter a name",
    nameLong: "The name is too long",
    nameOneWord: "Name — one word, no spaces",
    needPhone: "Enter a phone number",
    phoneLong: "Phone: 13 characters maximum",
    phoneFormat: "Digits only; “+” can go at the start",
  },
};

export const copy = { ru, en } as const;
export type Copy = typeof ru;
export type CopySeoPath = keyof typeof ru.seo;
